# see http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CC=gcc-4.9 CXX=g++-4.9
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: CC=clang-3.6 CXX=clang++-3.6


# check environment (copied from libgit2sharp)
before_install:
- date -u
- uname -a
- sudo apt-get update -qq

# TODO: could move script to separate file
# Not running unit tests at the moment, so turn off testing, which will
# hopefully make OS X builds a bit faster
script:
  - cd bin
  - cmake -DDOWNLOAD_TOOLKITS:BOOL=OFF -DBUILD_TESTING:BOOL=OFF ../Superbuild
  - make -j8
#  make SCIRunTestData_external
#  && make test

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
